### PR TITLE
Update composer.json with stable middleman, bump some version numbers.

### PR DESCRIPTION
**Pull request by Zegnat**
Does what it says on the tin.

I have been using fermi for small quick projects, as it bundles all the HTTP-handling packages I would use anyway. Just updating it with this.

### CODE REVIEW

**Comment by Zegnat** [comment]
And of course this breaks stuff because of the middleware interface updates. Oops. Working on it.

**Comment by Zegnat** [comment]
The update-packages branch is now what I use. Feel free to pull / merge / cherry-pick / ignore.

**Comment by joshuabryant** [comment]
Thanks, @Zegnat, for the PR! Will review tomorrow morning and get back to you.

**Comment by joshuabryant** [comment]
@Zegnat We've rolled this into a new PR (#2). Thanks for helping us move the framework forward!

**Pull request closed without merging**
